Name: Prasana Shangloo

Roll No: 23102A0076

Class: CMPN - A

R-Programming Week 9

In [1]:
try(print("The zero occurs at", 2*pi, "radians."))

Error in print.default("The zero occurs at", 2 * pi, "radians.") :
  invalid 'quote' argument

In [2]:
print("The zero occurs at"); print(2*pi); print("radians")
cat("The zero occurs at", 2*pi, "radians.", "\n")

[1] "The zero occurs at"
[1] 6.283185
[1] "radians"
The zero occurs at 6.283185 radians.

In [3]:
d = date()
cat("Today's date is:", d, "\n")

Today's date is: Thu Oct  1 08:43:55 2026

In [4]:
x = 1:10
x
cat(x, sep = " ++ ")
cat("\n")
cat(x, sep = " / ")

 [1]  1  2  3  4  5  6  7  8  9 10

1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10
1 / 2 / 3 / 4 / 5 / 6 / 7 / 8 / 9 / 10

In [5]:
x = 7
cat("The square of", x, "is", x^2, "!\n")

The square of 7 is 49 !

In [6]:
cat("The square root of", x, "is approximately", format(sqrt(x), digits=3), "\n")

The square root of 7 is approximately 2.65

In [7]:
evenno = c(2,4,6,8,10)
evenno
cat("The first few even numbers are:", evenno, "...\n")

[1]  2  4  6  8 10

The first few even numbers are: 2 4 6 8 10 ...

In [8]:
x = 1:10
x
cat(x, fill = 2, labels = paste("(", letters[1:10], "):"))

 [1]  1  2  3  4  5  6  7  8  9 10

( a ): 1
( b ): 2
( c ): 3
( d ): 4
( e ): 5
( f ): 6
( g ): 7
( h ): 8
( i ): 9
( j ): 10

In [9]:
paste(1:12)
as.character(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [10]:
paste("Everybody", "loves", "R Programming.")
paste("Everybody", "loves", "R Programming.", sep="*")
paste("Everybody", "loves", "R Programming.", sep="===")

[1] "Everybody loves R Programming."

[1] "Everybody*loves*R Programming."

[1] "Everybody===loves===R Programming."

In [11]:
names = c("Prof. Singh", "Mr.  Venkat", "Dr. Jha")
names
paste(names, "is", "a good", "person.")

[1] "Prof. Singh" "Mr.  Venkat" "Dr. Jha"

[1] "Prof. Singh is a good person." "Mr.  Venkat is a good person."
[3] "Dr. Jha is a good person."

In [12]:
names = c("Prof. Singh", "Mr.  Venkat", "Dr. Jha")
paste(names, "is", "a good", "person.", collapse=", and ")

[1] "Prof. Singh is a good person., and Mr.  Venkat is a good person., and Dr. Jha is a good person."

In [13]:
paste(1, " is first", 2, " is second", 3, " is third", sep = "#")
paste(1, " is first    ", 2, " is second      ", 3, " is third    ", sep = "#")

[1] "1# is first#2# is second#3# is third"

[1] "1# is first    #2# is second      #3# is third    "

In [14]:
x = paste("Ex", 1:5, sep="_")
x
x[1]
x[2]
x[3]
x[4]
x[5]

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

[1] "Ex_1"

[1] "Ex_2"

[1] "Ex_3"

[1] "Ex_4"

[1] "Ex_5"

In [15]:
x = paste("Ex", 1:5, sep="_", collapse="")
x
x[1]

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

In [16]:
x = paste("Ex", 1:5, sep="_")
x
x = paste("Ex", 1:5, sep="_", collapse="")
x

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

In [17]:
paste0(1:10)
paste(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [18]:
paste0(1:10, c("st", "nd", "rd", rep("th", 7)))
paste(1:10, c("st", "nd", "rd", rep("th", 7)))

 [1] "1st"  "2nd"  "3rd"  "4th"  "5th"  "6th"  "7th"  "8th"  "9th"  "10th"

 [1] "1 st"  "2 nd"  "3 rd"  "4 th"  "5 th"  "6 th"  "7 th"  "8 th"  "9 th"
[10] "10 th"

In [19]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"
x
strsplit(x, split = "!")

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

[[1]]
[1] "The&"                "syntax&"             "of&"
[4] "paste&"              "is"                  "&available"
[7] " &inthe online-help"

In [20]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"
x
strsplit(x, split = "&!")

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

[[1]]
[1] "The"                               "syntax"
[3] "of"                                "paste"
[5] "is!&available! &inthe online-help"

In [21]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"
x
y = strsplit(x, split = "!&")
y
y[[1]][1]
y[[1]][2]
y[[1]][3]

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

[[1]]
[1] "The&!syntax&!of&!paste&!is"    "available! &inthe online-help"

[1] "The&!syntax&!of&!paste&!is"

[1] "available! &inthe online-help"

[1] NA

In [22]:
dates = c("2020-07-24", "2021-08-25", "2022-09-26", "2023-10-27")
dates
datesplt = strsplit(dates, "-")
datesplt
datemat = matrix(unlist(datesplt), nrow = 4, ncol = 3, byrow = TRUE)
datemat
datematrix = matrix(as.numeric(unlist(datesplt)), nrow = 4, ncol = 3, byrow = TRUE)
datematrix

[1] "2020-07-24" "2021-08-25" "2022-09-26" "2023-10-27"

[[1]]
[1] "2020" "07"   "24"

[[2]]
[1] "2021" "08"   "25"

[[3]]
[1] "2022" "09"   "26"

[[4]]
[1] "2023" "10"   "27"

     [,1] [,2] [,3]
[1,] 2020 07   24
[2,] 2021 08   25
[3,] 2022 09   26
[4,] 2023 10   27

     [,1] [,2] [,3]
[1,] 2020  7   24
[2,] 2021  8   25
[3,] 2022  9   26
[4,] 2023 10   27

In [23]:
strsplit("Shalabh", split = "")

[[1]]
[1] "S" "h" "a" "l" "a" "b" "h"

In [24]:
x = "R course 24.07.2022"
x
y = "Number of participants: 25"
y
nchar(x)
nchar(y)
nzchar(x)
nzchar(y)

[1] "R course 24.07.2022"

[1] "Number of participants: 25"

[1] 19

[1] 26

[1] TRUE

[1] TRUE

In [25]:
x = c("Apple", "Banana", "Cake")
x
nzchar(x)
y = c("Apple", "", "Cake")
y
nzchar(y)

[1] "Apple"  "Banana" "Cake"

[1] TRUE TRUE TRUE

[1] "Apple" ""      "Cake"

[1]  TRUE FALSE  TRUE

In [26]:
x = c("Apple", "Banana", "Cake")
nchar(x)
y = c(2, 4, 6)
nchar(y)
z = c(11, 222, 3333)
nchar(z)
z1 = c(1.1, 2.22, 3.333)
nchar(z1)

[1] 5 6 4

[1] 1 1 1

[1] 2 3 4

[1] 3 4 5

In [27]:
x = "R course will start from 24.07.2022"
x
toupper(x)
z = "INDIAN INSTITUTE OF TECHNOLOGY"
z
tolower(z)

[1] "R course will start from 24.07.2022"

[1] "R COURSE WILL START FROM 24.07.2022"

[1] "INDIAN INSTITUTE OF TECHNOLOGY"

[1] "indian institute of technology"